opt_in_rules: # rule identifiers turned on by default to exclude from running
    - file_length #Gives Error
    - type_body_length
    - colon
    - mark
    - line_length
    - type_name
    - cyclomatic_complexity
    - large_tuple
    - function_body_length
    - trailing_semicolon
    - control_statement
    - comment_spacing
    - redundant_discardable_let
    - class_delegate_protocol
    - todo
    - implicit_getter
    - vertical_whitespace
    - notification_center_detachment
    - for_where
    - trailing_newline
    - syntactic_sugar
    - comma
    - unused_closure_parameter
    - opening_brace
    - redundant_optional_initialization
    - statement_position
    - identifier_name
    - trailing_comma
    - empty_parameters
    - leading_whitespace
    - void_return
    - empty_parentheses_with_trailing_closure
    - function_parameter_count
    - legacy_constructor
    - inclusive_language
    - redundant_objc_attribute
    - unused_optional_binding
    - empty_enum_arguments
    - block_based_kvo
    - no_space_in_method_call
    - duplicate_imports
    - compiler_protocol_init
    - unneeded_break_in_switch
    - closure_parameter_position
    - closing_brace
    - discouraged_direct_init
    - force_unwrapping
    - weak_delegate
    - force_cast
    - force_try
    - duplicate_enum_cases
    - dynamic_inline
    - unused_setter_value
    - prohibited_super_call
    - flatmap_over_map_reduce
    - deployment_target
#    - empty_count # Gives error

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - External
  - PokedexTests/
  - PokedexUITests/

disabled_rules:
  - identifier_name
  - redundant_string_enum_value
  - cyclomatic_complexity
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - nesting

line_length:
  warning: 200
  error: 400
  
vertical_whitespace:
  max_empty_lines: 2

